version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0-arm64
    environment:
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9200']
      interval: 10s
      timeout: 5s
      retries: 3

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0-arm64
    ports:
      - 5601:5601
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5601']
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      elasticsearch:
        condition: service_healthy

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.5.0-arm64
    ports:
      - 8200:8200
    environment:
      - apm-server.host="0.0.0.0:8200"
      - output.elasticsearch.hosts=['elasticsearch:9200']
      - setup.kibana.host="kibana:5601"
  
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy