heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://elasticsearch:9200
    - http://kibana:5601
    #- http://front:3000

- type: icmp
  schedule: '@every 5s'
  hosts:
    - elasticsearch
    - kibana
    - apm
    - metricbeat

processors:
- add_cloud_metadata: ~

setup.kibana.host: kibana:5601
output.elasticsearch:
  hosts: 'elasticsearch:9200'
  username: 'elastic'
  password: 'changeme'